baseURL = 'https://rachelsohzc.netlify.app/'
languageCode = 'en-us'
title = "Rachel's Journal"
theme = "dream"

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "rachel"
avatar = "/main-images/kayak-profile.jpeg"
headerTitle = "rachel"
motto = "journal of an INFP"

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

siteStartYear = 2024

favicon = "/favicon.ico"

[params.advanced]
customCSS = ["css/custom.css"]
customJS = []

[params.dates]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

# Syntax highlighting
customSyntaxHighlighting = true

stickyNav = true
showSummaryCoverInPost = true